name: tes
description: "A new Flutter project."
publish_to: "none" # proyek tidak akan dipublikasikan ke pub.dev (hanya untuk lokal)

version: 1.0.0+1 # versi aplikasi (1.0.0) + build number (1)

environment:
  sdk: ^3.5.4 # versi minimum SDK Dart yang digunakan

dependencies:
  flutter:
    sdk: flutter

  # ✅ FONT & UI
  google_fonts: ^6.2.1 # untuk menggunakan font dari Google Fonts (misal Poppins)
  cupertino_icons: ^1.0.8 # ikon gaya iOS
  
  # ✅ GAMBAR & MODEL MACHINE LEARNING
  image_picker: ^1.1.2 # ambil gambar dari kamera atau galeri
  tflite_flutter: ^0.11.0 # menjalankan model TensorFlow Lite (deteksi stres)
  image: ^4.5.2 # manipulasi gambar (resize, decoding, dsb)
  google_mlkit_face_detection: ^0.13.1 # deteksi wajah menggunakan ML Kit Google
  
  # ✅ STATE MANAGEMENT & PENYIMPANAN
  provider: ^6.1.1 # state management, digunakan untuk RiwayatProvider
  intl: ^0.18.1 # format tanggal & jam lokal (misalnya Indonesia)
  path_provider: ^2.1.2 # akses direktori penyimpanan lokal perangkat (untuk simpan file JSON riwayat)

dev_dependencies:
  flutter_launcher_icons: ^0.13.1 # mengatur ikon aplikasi (logo utama)
flutter_launcher_icons:
  android: true
  ios: false
  image_path: "assets/icon/logo.png" # lokasi ikon aplikasi

  flutter_test:
    sdk: flutter # untuk testing Flutter (opsional)

  flutter_lints: ^4.0.0 # aturan coding style dan rekomendasi best practice dari Flutter

flutter:
  uses-material-design: true # aktifkan penggunaan ikon Material Design bawaan Flutter

  # ✅ ASET GAMBAR & MODEL
  assets:
    - assets/gambar/ # folder berisi gambar umum (misalnya untuk UI)
    - assets/model/model_stress.tflite # model TensorFlow Lite untuk klasifikasi stres
    - assets/model/label.txt # label kelas dari model (misalnya [Normal, Stres])
    - assets/gambar/petunjuk.png # gambar instruksi pada halaman petunjuk

  # ✅ FONT CUSTOM
  fonts:
    - family: Poppins # nama font family yang digunakan di seluruh aplikasi
      fonts:
        - asset: assets/font/Poppins-Regular.ttf
        - asset: assets/font/Poppins-Bold.ttf
          weight: 700
        - asset: assets/font/Poppins-SemiBold.ttf
          weight: 600
        - asset: assets/font/Poppins-Medium.ttf
          weight: 500
